# Generated by Django 4.1.6 on 2023-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doesnotexist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
