# Generated by Django 4.1.6 on 2023-02-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=255, unique=True),
        ),
    ]
