# Generated by Django 4.1.5 on 2023-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
