# Generated by Django 4.1.5 on 2023-01-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0002_file_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='emails_sent',
            field=models.IntegerField(default=0),
        ),
    ]
