# Generated by Django 4.1.5 on 2023-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_file_emails_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='emails_sent',
            field=models.IntegerField(),
        ),
    ]
