# Generated by Django 4.1.5 on 2023-01-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0004_alter_file_emails_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='emails_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
