# Generated by Django 4.1.6 on 2023-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0005_alter_file_emails_sent_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
